### ISSUE TITLE
GRANT RECIPIENTS: Unclear "ECLIPSE V2"

### ISSUE THREAD

**Issue by Chealer** [ossf/alpha-omega#349]
[The list of Alpha grant recipients](https://alpha-omega.dev/grants/grantrecipients/) includes "ECLIPSE V2" in 2023. One guesses that "V2" means "version 2", but it is unclear what "Eclipse version 2" means.

Inspection of the whole page reveals that Eclipse also received a grant in 2022, making the 2023 grant the second. I therefore suppose that "ECLIPSE V2" means "Second grant to the Eclipse Foundation".

<details>
  <summary>By the way</summary>
"Eclipse" is a highly ambiguous term which can notably refer to a platform, a product and a project. The title would be much clearer if it specified "Foundation".
</details>

**Comment by scovetta** [comment]
Thanks @Chealer, I've updated the text to say "Eclipse Foundation" and removed the v2 designation.
