### ISSUE TITLE
Please use double-dash instead of single-dash for long name options

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/alpha-omega#35]
Most Unix/POSIX tools have an option convention of `-` followed by a collection of single-letter options, and `--` followed by a single long-name option. [Long options came from GNU](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html#:~:text=Long%20options%20consist%20of%20%2D%2D,%2C%20write%20%2D%2D%20name%20%3D%20value%20.) but many other tools also support them. E.g.:

~~~~
ls -ad
ls --all --directory
~~~~

So I think:
~~~~
osf generate –assertion reproducible -subject pkg:npm/left-pad@1.3.0 –repository assertions.openssf.org
~~~~
Should be:
~~~~
osf generate --assertion reproducible --subject pkg:npm/left-pad@1.3.0 --repository assertions.openssf.org
~~~~

If this is already happening, and it's just misleading due to markdown formatting, then never mind... :-).

**Comment by david-a-wheeler** [comment]
@scovetta - I wasn't sure if this was the right project to post to, but I figured it'd be best to put this *somewhere*.

**Comment by scovetta** [comment]
Confirmed, all switches are double dashes.
